/* The following code was generated by JFlex 1.6.1 */

package analisislexico;
import static analisislexico.Token.*;
import java_cup.runtime.Symbol;
import java.io.Reader;

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.6.1
 * from the specification file <tt>src/analisislexico/lexer.flex</tt>
 */
class Lexer {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\3\1\5\1\6\1\6\1\5\22\0\1\3\1\14\1\0"+
    "\1\4\2\0\1\21\1\7\1\23\1\10\1\16\1\15\1\63\1\17"+
    "\1\61\1\20\12\2\1\0\1\62\1\12\1\11\1\13\2\0\1\54"+
    "\3\1\1\57\3\1\1\52\5\1\1\47\1\56\1\1\1\60\10\1"+
    "\1\26\1\0\1\27\1\0\1\1\1\0\1\46\1\35\1\34\1\40"+
    "\1\31\1\32\1\36\1\53\1\37\2\1\1\50\1\51\1\33\1\43"+
    "\2\1\1\30\1\42\1\44\1\41\1\55\1\45\3\1\1\24\1\22"+
    "\1\25\7\0\1\6\u1fa2\0\1\6\1\6\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\udfe6\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\2\4\1\1\1\5\1\6"+
    "\1\7\1\10\1\11\1\12\1\13\1\14\1\15\2\1"+
    "\1\16\1\17\1\20\1\21\1\22\17\2\1\23\1\24"+
    "\2\0\1\25\1\26\1\27\1\30\1\3\1\31\1\32"+
    "\10\2\1\33\1\34\17\2\1\35\1\36\2\2\1\37"+
    "\1\2\1\40\4\2\1\41\1\42\1\2\1\43\1\2"+
    "\1\44\13\2\1\45\1\46\6\2\1\47\5\2\1\50"+
    "\1\2\1\51\3\2\1\52\1\53\1\54\2\2\1\55"+
    "\3\2\1\56\2\2\1\57\6\2\1\60\2\2\1\61"+
    "\2\2\1\62\1\63\1\2\1\64\4\2\1\65\1\66"+
    "\1\67\1\70\1\71";

  private static int [] zzUnpackAction() {
    int [] result = new int[160];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\64\0\150\0\234\0\64\0\320\0\u0104\0\64"+
    "\0\u0138\0\u016c\0\u01a0\0\u01d4\0\u0208\0\64\0\u0208\0\64"+
    "\0\u023c\0\u0270\0\64\0\64\0\64\0\64\0\64\0\u02a4"+
    "\0\u02d8\0\u030c\0\u0340\0\u0374\0\u03a8\0\u03dc\0\u0410\0\u0444"+
    "\0\u0478\0\u04ac\0\u04e0\0\u0514\0\u0548\0\u057c\0\64\0\64"+
    "\0\u05b0\0\u05e4\0\64\0\64\0\64\0\64\0\u0208\0\64"+
    "\0\64\0\u0618\0\u064c\0\u0680\0\u06b4\0\u06e8\0\u071c\0\u0750"+
    "\0\u0784\0\150\0\u07b8\0\u07ec\0\u0820\0\u0854\0\u0888\0\u08bc"+
    "\0\u08f0\0\u0924\0\u0958\0\u098c\0\u09c0\0\u09f4\0\u0a28\0\u0a5c"+
    "\0\u0a90\0\u0ac4\0\u05b0\0\64\0\u0af8\0\u0b2c\0\150\0\u0b60"+
    "\0\150\0\u0b94\0\u0bc8\0\u0bfc\0\u0c30\0\150\0\150\0\u0c64"+
    "\0\150\0\u0c98\0\150\0\u0ccc\0\u0d00\0\u0d34\0\u0d68\0\u0d9c"+
    "\0\u0dd0\0\u0e04\0\u0e38\0\u0e6c\0\u0ea0\0\u0ed4\0\150\0\150"+
    "\0\u0f08\0\u0f3c\0\u0f70\0\u0fa4\0\u0fd8\0\u100c\0\150\0\u1040"+
    "\0\u1074\0\u10a8\0\u10dc\0\u1110\0\150\0\u1144\0\150\0\u1178"+
    "\0\u11ac\0\u11e0\0\150\0\150\0\150\0\u1214\0\u1248\0\150"+
    "\0\u127c\0\u12b0\0\u12e4\0\150\0\u1318\0\u134c\0\150\0\u1380"+
    "\0\u13b4\0\u13e8\0\u141c\0\u1450\0\u1484\0\150\0\u14b8\0\u14ec"+
    "\0\150\0\u1520\0\u1554\0\150\0\150\0\u1588\0\150\0\u15bc"+
    "\0\u15f0\0\u1624\0\u1658\0\150\0\150\0\150\0\150\0\150";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[160];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\5\1\6\1\5\1\0\1\7"+
    "\1\10\1\11\1\12\1\13\1\14\1\15\1\16\1\17"+
    "\1\20\1\21\1\22\1\23\1\24\1\25\1\26\1\27"+
    "\1\30\1\31\1\32\2\3\1\33\1\3\1\34\1\35"+
    "\1\36\1\37\1\40\1\41\1\42\1\43\1\3\1\44"+
    "\2\3\1\45\1\3\1\46\3\3\1\2\1\47\1\50"+
    "\65\0\2\3\25\0\31\3\5\0\1\4\56\0\1\51"+
    "\2\0\5\6\2\0\55\6\7\52\2\0\12\52\1\0"+
    "\40\52\11\0\1\53\63\0\1\54\63\0\1\55\63\0"+
    "\1\56\54\0\1\57\102\0\1\60\64\0\1\61\42\0"+
    "\2\3\25\0\1\3\1\62\27\3\4\0\2\3\25\0"+
    "\3\3\1\63\14\3\1\64\10\3\4\0\2\3\25\0"+
    "\13\3\1\65\2\3\1\66\1\3\1\67\10\3\4\0"+
    "\2\3\25\0\1\3\1\70\11\3\1\71\15\3\4\0"+
    "\2\3\25\0\2\3\1\72\1\73\25\3\4\0\2\3"+
    "\25\0\1\3\1\74\5\3\1\75\21\3\4\0\2\3"+
    "\25\0\12\3\1\76\16\3\4\0\2\3\25\0\21\3"+
    "\1\77\7\3\4\0\2\3\25\0\11\3\1\100\17\3"+
    "\4\0\2\3\25\0\1\101\1\102\7\3\1\103\1\3"+
    "\1\104\15\3\4\0\2\3\25\0\1\105\30\3\4\0"+
    "\2\3\25\0\3\3\1\106\25\3\4\0\2\3\25\0"+
    "\13\3\1\107\15\3\4\0\2\3\25\0\11\3\1\110"+
    "\17\3\4\0\2\3\25\0\13\3\1\111\2\3\1\112"+
    "\12\3\5\0\1\113\70\0\1\114\55\0\2\3\25\0"+
    "\2\3\1\115\13\3\1\116\12\3\4\0\2\3\25\0"+
    "\10\3\1\117\20\3\4\0\2\3\25\0\12\3\1\120"+
    "\16\3\4\0\2\3\25\0\1\121\30\3\4\0\2\3"+
    "\25\0\20\3\1\122\10\3\4\0\2\3\25\0\13\3"+
    "\1\123\15\3\4\0\2\3\25\0\6\3\1\124\22\3"+
    "\4\0\2\3\25\0\13\3\1\125\15\3\4\0\2\3"+
    "\25\0\14\3\1\126\14\3\4\0\2\3\25\0\2\3"+
    "\1\127\26\3\4\0\2\3\25\0\6\3\1\130\22\3"+
    "\4\0\2\3\25\0\1\3\1\131\27\3\4\0\2\3"+
    "\25\0\16\3\1\132\12\3\4\0\2\3\25\0\14\3"+
    "\1\133\14\3\4\0\2\3\25\0\11\3\1\134\17\3"+
    "\4\0\2\3\25\0\21\3\1\135\7\3\4\0\2\3"+
    "\25\0\1\136\30\3\4\0\2\3\25\0\30\3\1\137"+
    "\4\0\2\3\25\0\7\3\1\140\21\3\4\0\2\3"+
    "\25\0\16\3\1\141\12\3\4\0\2\3\25\0\3\3"+
    "\1\142\25\3\4\0\2\3\25\0\21\3\1\143\7\3"+
    "\4\0\2\3\25\0\7\3\1\144\21\3\4\0\2\3"+
    "\25\0\20\3\1\145\10\3\4\0\2\3\25\0\1\3"+
    "\1\146\27\3\4\0\2\3\25\0\10\3\1\147\20\3"+
    "\4\0\2\3\25\0\1\3\1\150\27\3\4\0\2\3"+
    "\25\0\12\3\1\151\16\3\4\0\2\3\25\0\16\3"+
    "\1\152\12\3\4\0\2\3\25\0\7\3\1\153\21\3"+
    "\4\0\2\3\25\0\20\3\1\154\10\3\4\0\2\3"+
    "\25\0\7\3\1\155\21\3\4\0\2\3\25\0\20\3"+
    "\1\156\10\3\4\0\2\3\25\0\1\3\1\157\27\3"+
    "\4\0\2\3\25\0\22\3\1\160\6\3\4\0\2\3"+
    "\25\0\3\3\1\161\25\3\4\0\2\3\25\0\1\3"+
    "\1\162\27\3\4\0\2\3\25\0\14\3\1\163\14\3"+
    "\4\0\2\3\25\0\20\3\1\164\10\3\4\0\2\3"+
    "\25\0\6\3\1\165\22\3\4\0\2\3\25\0\24\3"+
    "\1\166\4\3\4\0\2\3\25\0\10\3\1\167\20\3"+
    "\4\0\2\3\25\0\26\3\1\170\1\171\1\3\4\0"+
    "\2\3\25\0\1\172\30\3\4\0\2\3\25\0\1\3"+
    "\1\173\27\3\4\0\2\3\25\0\14\3\1\174\14\3"+
    "\4\0\2\3\25\0\3\3\1\175\25\3\4\0\2\3"+
    "\25\0\1\3\1\176\27\3\4\0\2\3\25\0\14\3"+
    "\1\177\14\3\4\0\2\3\25\0\20\3\1\200\10\3"+
    "\4\0\2\3\25\0\10\3\1\201\20\3\4\0\2\3"+
    "\25\0\17\3\1\202\11\3\4\0\2\3\25\0\14\3"+
    "\1\203\14\3\4\0\2\3\25\0\1\3\1\204\27\3"+
    "\4\0\2\3\25\0\13\3\1\205\15\3\4\0\2\3"+
    "\25\0\21\3\1\206\7\3\4\0\2\3\25\0\23\3"+
    "\1\207\5\3\4\0\2\3\25\0\20\3\1\210\10\3"+
    "\4\0\2\3\25\0\1\3\1\211\27\3\4\0\2\3"+
    "\25\0\16\3\1\212\12\3\4\0\2\3\25\0\16\3"+
    "\1\213\12\3\4\0\2\3\25\0\1\3\1\214\27\3"+
    "\4\0\2\3\25\0\2\3\1\215\1\216\25\3\4\0"+
    "\2\3\25\0\11\3\1\217\17\3\4\0\2\3\25\0"+
    "\6\3\1\220\22\3\4\0\2\3\25\0\5\3\1\221"+
    "\23\3\4\0\2\3\25\0\1\3\1\222\27\3\4\0"+
    "\2\3\25\0\3\3\1\223\25\3\4\0\2\3\25\0"+
    "\3\3\1\224\25\3\4\0\2\3\25\0\20\3\1\225"+
    "\10\3\4\0\2\3\25\0\16\3\1\226\12\3\4\0"+
    "\2\3\25\0\2\3\1\227\26\3\4\0\2\3\25\0"+
    "\1\230\30\3\4\0\2\3\25\0\7\3\1\231\21\3"+
    "\4\0\2\3\25\0\4\3\1\232\24\3\4\0\2\3"+
    "\25\0\4\3\1\233\24\3\4\0\2\3\25\0\20\3"+
    "\1\234\10\3\4\0\2\3\25\0\3\3\1\235\25\3"+
    "\4\0\2\3\25\0\4\3\1\236\24\3\4\0\2\3"+
    "\25\0\14\3\1\237\14\3\4\0\2\3\25\0\1\3"+
    "\1\240\27\3\3\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[5772];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\2\1\1\11\2\1\1\11\5\1\1\11"+
    "\1\1\1\11\2\1\5\11\17\1\2\11\2\0\4\11"+
    "\1\1\2\11\32\1\1\11\124\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[160];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */
public String lexeme;
private TablaSimbolos tabla;
Lexer(Reader in,TablaSimbolos t){
    this(in);
    this.tabla=t;
    }

public int linea;


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Lexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 186) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public Token yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          zzR = false;
          break;
        case '\r':
          yyline++;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
          }
          break;
        default:
          zzR = false;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
        return null;
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { lexeme=yytext(); linea=yyline; return ERROR;
            }
          case 58: break;
          case 2: 
            { lexeme=yytext(); linea=yyline; 
                Simbolo s;
                if((s=tabla.buscar(lexeme))==null)
                    s=tabla.insertar(lexeme);return ID;
            }
          case 59: break;
          case 3: 
            { lexeme=yytext(); linea=yyline; return entero;
            }
          case 60: break;
          case 4: 
            { /* ignore */
            }
          case 61: break;
          case 5: 
            { lexeme=yytext(); linea=yyline; return PARCI;
            }
          case 62: break;
          case 6: 
            { lexeme=yytext();linea=yyline; return ASIG;
            }
          case 63: break;
          case 7: 
            { lexeme=yytext(); linea=yyline; return MENQ;
            }
          case 64: break;
          case 8: 
            { lexeme=yytext(); linea=yyline; return MAYQ;
            }
          case 65: break;
          case 9: 
            { lexeme=yytext(); linea=yyline; return NOT;
            }
          case 66: break;
          case 10: 
            { lexeme=yytext(); linea=yyline; return SUM;
            }
          case 67: break;
          case 11: 
            { lexeme=yytext(); linea=yyline; return MUL;
            }
          case 68: break;
          case 12: 
            { lexeme=yytext(); linea=yyline; return MEN;
            }
          case 69: break;
          case 13: 
            { lexeme=yytext(); linea=yyline; return DIV;
            }
          case 70: break;
          case 14: 
            { lexeme=yytext(); linea=yyline; return PARAB;
            }
          case 71: break;
          case 15: 
            { lexeme=yytext(); linea=yyline; return LLAVAB;
            }
          case 72: break;
          case 16: 
            { lexeme=yytext(); linea=yyline; return LLAVCI;
            }
          case 73: break;
          case 17: 
            { lexeme=yytext(); linea=yyline; return CORAB;
            }
          case 74: break;
          case 18: 
            { lexeme=yytext(); linea=yyline; return CORCI;
            }
          case 75: break;
          case 19: 
            { lexeme=yytext(); linea=yyline; return ENDLN;
            }
          case 76: break;
          case 20: 
            { lexeme=yytext(); linea=yyline; return COMA;
            }
          case 77: break;
          case 21: 
            { lexeme=yytext(); linea=yyline; return IGUAL;
            }
          case 78: break;
          case 22: 
            { lexeme=yytext(); linea=yyline; return MENIQ;
            }
          case 79: break;
          case 23: 
            { lexeme=yytext(); linea=yyline; return MAYIQ;
            }
          case 80: break;
          case 24: 
            { lexeme=yytext(); linea=yyline; return DIF;
            }
          case 81: break;
          case 25: 
            { lexeme=yytext(); linea=yyline; return AND;
            }
          case 82: break;
          case 26: 
            { lexeme=yytext(); linea=yyline; return OR;
            }
          case 83: break;
          case 27: 
            { lexeme=yytext(); linea=yyline; return If;
            }
          case 84: break;
          case 28: 
            { lexeme=yytext(); linea=yyline; return In;
            }
          case 85: break;
          case 29: 
            { lexeme=yytext(); linea=yyline; return flotante;
            }
          case 86: break;
          case 30: 
            { /*Ignore*/
            }
          case 87: break;
          case 31: 
            { lexeme=yytext(); linea=yyline; return end;
            }
          case 88: break;
          case 32: 
            { lexeme=yytext(); linea=yyline; return For;
            }
          case 89: break;
          case 33: 
            { lexeme=yytext(); linea=yyline; return Int;
            }
          case 90: break;
          case 34: 
            { lexeme=yytext(); linea=yyline; return def;
            }
          case 91: break;
          case 35: 
            { lexeme=yytext(); linea=yyline; return use;
            }
          case 92: break;
          case 36: 
            { lexeme=yytext(); linea=yyline; return Out;
            }
          case 93: break;
          case 37: 
            { lexeme=yytext(); linea=yyline; return read;
            }
          case 94: break;
          case 38: 
            { lexeme=yytext(); linea=yyline; return Else;
            }
          case 95: break;
          case 39: 
            { lexeme=yytext(); linea=yyline; return True;
            }
          case 96: break;
          case 40: 
            { lexeme=yytext(); linea=yyline; return Long;
            }
          case 97: break;
          case 41: 
            { lexeme=yytext(); linea=yyline; return Void;
            }
          case 98: break;
          case 42: 
            { lexeme=yytext(); linea=yyline; return False;
            }
          case 99: break;
          case 43: 
            { lexeme=yytext(); linea=yyline; return Float;
            }
          case 100: break;
          case 44: 
            { lexeme=yytext(); linea=yyline; return begin;
            }
          case 101: break;
          case 45: 
            { lexeme=yytext(); linea=yyline; return small;
            }
          case 102: break;
          case 46: 
            { lexeme=yytext(); linea=yyline; return write;
            }
          case 103: break;
          case 47: 
            { lexeme=yytext(); linea=yyline; return valPh;
            }
          case 104: break;
          case 48: 
            { lexeme=yytext(); linea=yyline; return turnOn;
            }
          case 105: break;
          case 49: 
            { lexeme=yytext(); linea=yyline; return humAmb;
            }
          case 106: break;
          case 50: 
            { lexeme=yytext(); linea=yyline; return Boolean;
            }
          case 107: break;
          case 51: 
            { lexeme=yytext(); linea=yyline; return digital;
            }
          case 108: break;
          case 52: 
            { lexeme=yytext(); linea=yyline; return turnOff;
            }
          case 109: break;
          case 53: 
            { lexeme=yytext(); linea=yyline; return temIdeal;
            }
          case 110: break;
          case 54: 
            { lexeme=yytext(); linea=yyline; return toReturn;
            }
          case 111: break;
          case 55: 
            { lexeme=yytext(); linea=yyline; return analogic;
            }
          case 112: break;
          case 56: 
            { lexeme=yytext(); linea=yyline; return valElect;
            }
          case 113: break;
          case 57: 
            { lexeme=yytext(); linea=yyline; return reference;
            }
          case 114: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
